version: '3.7'

services:
  db:
    image: postgres
    container_name: movie_db
    restart: always
    volumes:
      - ./data/pgdata:/var/lib/postgresql/my_data
    env_file:
      - ../../.env
    ports:
      - "5454:5432"
    command: ["postgres", "-c", "log_statement=all"]
