# Generated by Django 4.2 on 2023-04-29 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("recommendation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwatchedmovie",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="platforms",
            field=models.ManyToManyField(related_name="movies", to="movie.platform"),
        ),
        migrations.AddField(
            model_name="movie",
            name="recommenders",
            field=models.ManyToManyField(
                blank=True,
                related_name="recommend_movies",
                through="recommendation.UserRecommendMovie",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="watchers",
            field=models.ManyToManyField(
                blank=True,
                related_name="watched_movies",
                through="movie.UserWatchedMovie",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userwatchedmovie",
            unique_together={("user", "movie")},
        ),
    ]
